### ISSUE TITLE
AWS Device Farm doesn't recognise tests

### ISSUE THREAD

**Issue by MartijnSchoemaker** [net-a-porter-mobile/XCTest-Gherkin#101]
Last time we implemented a lot of tests with XCTest-Gherkin. They are running smooth on a local machine. Now we want to run the tests in AWS Device Farm, they support XCTest UI, so our tests should run there.

But when I upload our UITests-Runner ipa to AWS and start the app, the tests are no recognised and no tests did run. At first I thought is has something to do with inheritance; if the class does not inherit from XCTestCase but some other class, that should probably not work. But I tried to implement my own inheritance chain based on NativeTestCase, but then the testcase was recognised in AWS and did run smoothly. 

This does not work in AWS (it does on a local machine):
```
import XCTest
import XCTest_Gherkin

class MyTestCase  : NativeTestCase {
}
```

This **does** work in AWS:
```
import XCTest
import XCTest_Gherkin

class MyXCGNativeInitializer : XCTestCase {
}

class MyNativeTestCase : MyXCGNativeInitializer {
}

class MyTestCase  : MyNativeTestCase {
}
```

**Comment by kerrmarin** [comment]
Probably due to the fact that the tests running on XCTest Gherkin are 'runtime tests' and the test classes are generated at runtime. I'd suggest opening a ticket with AWS.

Happy to look at a PR if you find the root cause is something related to this library.
