### ISSUE TITLE
Support swift package manager

### ISSUE THREAD

**Issue by deanWombourne** [net-a-porter-mobile/XCTest-Gherkin#109]
This shouldn't need any code changes, just adding a package.swift pointing at the right places for the source code. 

Our primary method of distribution will still be cocoapods, so we should leave everything in the default place for that and create a custom swift package manager config.

**Comment by anamsantos** [comment]
I guys.. any news abou that?

**Comment by deanWombourne** [comment]
Mostly this has dropped low down our list because we have no need for it. 

It turns out to be not as trivial as just adding a package.swift because we have some objective-c code in there :0

**Comment by Lucky1st** [comment]
@deanWombourne I hope you will add SPM support for your project. 
I know that this is not a decisive factor in choosing a tool for BDD. 
But it really saves time. Best regards.

**Comment by kerrmarin** [comment]
Looks like this was fixed in #171, can @anamsantos or @Lucky1st  confirm?
