### ISSUE TITLE
ENABLE_BITCODE error

### ISSUE THREAD

**Issue by BMe2U** [net-a-porter-mobile/XCTest-Gherkin#11]
ld: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I tried "ENABLE_BITCODE = No" it dint work, any help would be great!

**Comment by kerrmarin** [comment]
Hi @BMe2U,

We've never seen this issue before. It doesn't look related to this library however. Did you manage to find a fix for it?

**Comment by kerrmarin** [comment]
I'm closing this. Please let us know if you still have an issue while trying to use this library.

**Comment by ilife** [comment]
Faced the same issue. It happens when you select a device instead of simulator and test. Even the sample project also fails to build for device.

**Comment by kerrmarin** [comment]
@ilife I've made a PR to disable bitcode (https://github.com/net-a-porter-mobile/XCTest-Gherkin/pull/39). This will allow you to run on hardware devices.

**Comment by BMe2U** [comment]
I can see the ENABLE_BITCODE as "Yes", so i'm still getting the error.

**Comment by nap-sam-dean** [comment]
That's very strange :/ Quick sanity check - you've re-run `pod install`?

**Comment by kerrmarin** [comment]
A new version hasn't been released with #39 yet. @nap-sam-dean can you cut a new release from master? and @BMe2U can you try to point the podfile to HEAD and check if this solved your problem?

**Comment by nmcdonaldd** [comment]
My fix for this was to disable bitcode on the targets specified in project build settings.

**Comment by nap-sam-dean** [comment]
This has been pushed out as version 0.7.0 - let me know if it solves the problem. 

@nmcdonaldd Do you have an issue with having to reset that property each time you do a `pod install` / `pod update`?

**Comment by nap-sam-dean** [comment]
@BMe2U Hi - it's been 21 days sine any chat on this issue, we think it's fixed so unless you can confirm that it's not I'm going to close this issue in the next few days, thanks!

**Comment by nap-sam-dean** [comment]
I'm closing this because we think it's fixed and the OP has gone quiet on the matter.
