### ISSUE TITLE
Give @ilyapuchka merge access

### ISSUE THREAD

**Issue by kerrmarin** [net-a-porter-mobile/XCTest-Gherkin#117]
Hey Sam, since @ilyapuchka has been really pushing this forward the past few weeks I think it would be nice if he had merge access - if we can't do this because we're still under the NAP umbrella perhaps this is a good time to fork into our own org?

**Comment by ilyapuchka** [comment]
Yes, that would speed up a process for me definitely. We are using XCTest-Gherkin for automation on my current project and I'm working on improving our experience with automation tests, so contributing here will be important.

**Comment by deanWombourne** [comment]
@ilyapuchka You should get an invite soon :)

Just out of interest what's the project you're working on at the moment?

**Comment by ilyapuchka** [comment]
Thanks, got it!
It's [babylon health](https://www.babylonhealth.com).
