### ISSUE TITLE
Example should come after the steps, not before

### ISSUE THREAD

**Issue by deanWombourne** [net-a-porter-mobile/XCTest-Gherkin#12]
Feature files should allow the Example block to come after the Outline i.e.

```
Outline {
  Given("Some step with a <field_name>")
}

Examples(
   [ "field_name" ], 
   [ "value 1"],
   [ "value 2"])
```

should be a valid scenario.

**Comment by kerrmarin** [comment]
After discussing this change we decided the extra code was not worth this feature
