### ISSUE TITLE
Restarting app between scenarios in an outline (native parsing)

### ISSUE THREAD

**Issue by cameroncooke** [net-a-porter-mobile/XCTest-Gherkin#147]
When using native feature file parsing the current implementation treats a "Scenario Outline" and all the permutations as a single Test this means the test isn't torn down between runs and the app isn't therefore restarted.

This is causing problems for us as each test in our scenario outline expects to start from the same place. If the app doesn't restart we would have to unwind all the steps.

There doesn't appear to be a hook where we can restart the app once a scenario from an outline as finished.

**Comment by ilyapuchka** [comment]
I think you might use `Background` to restart the app and restore its state. `Background` is called before each example run.

**Comment by ilyapuchka** [comment]
Without background you can do that with a simple extension to avoid repeating code that restarts the app. This is what we use in our tests:

```swift
extension XCTestCase {
    func Outline(shouldTerminate: Bool, _ routine: ()->() ) {
        Outline {
            routine()
            if shouldTerminate {
                terminateApp()
            }
        }
    }
}
```
