### ISSUE TITLE
Xcode 11 issues

### ISSUE THREAD

**Issue by NSCabezon** [net-a-porter-mobile/XCTest-Gherkin#158]
hi I'm having some issues when trying to compile in Xcode 11 any ideas on why? 

<img width="348" alt="Captura de pantalla 2019-10-01 a las 13 47 53" src="https://user-images.githubusercontent.com/563761/65959395-29b9bb80-e452-11e9-829e-e0164bf56540.png">

PS: We don't want to enable legacy build system

**Comment by deanWombourne** [comment]
Hi,

I can't reproduce this in the Example project with Xcode 11.0, cocoapods 1.8.1.

How are you installing XCTest-Gherkin in your project?
