### ISSUE TITLE
Support for Xcode 12

### ISSUE THREAD

**Issue by joaobzao** [net-a-porter-mobile/XCTest-Gherkin#169]
Hey folks,

Using Xcode 12 beta, I tried to build `"net-a-porter-mobile/XCTest-Gherkin" == 0.19.2` using carthage and it failed due to:

```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in StringGherkinExtension.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you have any plans soon to support Xcode 12? 

Cheers 😄

**Comment by saarmstrong** [comment]
_bump_

**Comment by deanWombourne** [comment]
Hi - being blunt, pull requests are welcome. I'm a cocoapods user and don't really know enough about Carthage to help. Carthage support was added as a request from an external user and I've personally never used it.

That being said, I can take a look but honestly, you probably know more about the problem then I do at this point.

Sorry that's not much help.

**Comment by joaobzao** [comment]
Just tried to build it through carthage using latest xcode 12 beta 6 and I'm no longer experiencing the build issue described above. 🎉 

However we got a carthage builds fail at xcrun lipo. 

This is not a gherkin issue, I'm just leaving here this info in case someone steps into this problem.

This lipo issue is being discussed in **[this carthage issue](https://github.com/Carthage/Carthage/issues/3019)**, there are a lot of info and workarounds on the thread.

@deanWombourne  thanks for the reply and If you agree we can close this issue.
