### ISSUE TITLE
Can't import 0.19.2 with Swift Package Manager

### ISSUE THREAD

**Issue by pabloviciano** [net-a-porter-mobile/XCTest-Gherkin#174]
The library can't be imported from SPM because there isn't any Package.swift inside the source code. 

Please, could you fix it?

Cheers

**Comment by joaobzao** [comment]
It looks like there's no release tag with Package.swift

As a workaround you can try importing it pointing to `master` branch instead of a release tag.

![Screenshot 2020-11-03 at 18 04 41](https://user-images.githubusercontent.com/8434594/98023703-3bad2100-1dff-11eb-8c18-2feec848469f.png)

**Comment by deanWombourne** [comment]
Sigh, that's completely my fault - I've released it as version 0.20.0. Sorry about that :)
