### ISSUE TITLE
Support "But" keyword from Gherkin

### ISSUE THREAD

**Issue by jmp** [net-a-porter-mobile/XCTest-Gherkin#175]
Gherkin syntax includes a "But" keyword:
https://cucumber.io/docs/gherkin/reference/#and-but

For example:

> Given one thing
When I open my eyes
Then I should see something
But I shouldn't see something else

It's basically a synonym for "And", but in some cases makes the specification a bit more readable.

It would be nice if XCTest-Gherkin also supported this keyword.

**Comment by deanWombourne** [comment]
Hey - I've released this as 0.21.0 so you should be able to do a `pod update` :)
