### ISSUE TITLE
Native Feature files in subdirectories

### ISSUE THREAD

**Issue by tomleightonstars** [net-a-porter-mobile/XCTest-Gherkin#178]
Hi,

So I've got proper feature files in a folder called 'features'. I'm trying to add subdirectories to 'features' however the parser is attempting to open the folder as if it were a file and errors out.

Are subdirectories supported for the native feature files?

parseFeatureFile in NativeFeatureParser.swift is where the error is showing

**Comment by deanWombourne** [comment]
Hey - I guess if it's erroring out then no, no support for subfolders :) I'll make an issue and take a look - shouldn't be too hard to add in (said with hope).

**Comment by deanWombourne** [comment]
Yep - I can trivially reproduce this, it's definitely a bug.

**Comment by deanWombourne** [comment]
Hi - I've released this as version 0.21.1 - let me know if that works for you :)

**Comment by tomleightonstars** [comment]
thank you so much @deanWombourne! It works perfectly!
