### ISSUE TITLE
Early unexpected exit, operation never finished bootstrapping - no restart will be attempted

### ISSUE THREAD

**Issue by jgonfer** [net-a-porter-mobile/XCTest-Gherkin#31]
Hi there! When I try to run the UI Tests I get the following error message:

```
Test target XcuitUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
```

![image](https://cloud.githubusercontent.com/assets/5473123/16526383/5b55d67c-3fb1-11e6-8dc5-2b19f1d7baf7.png)

I'm using Xcode 7.3.1 and Cocoapods 1.0.1. You can check the project here: https://github.com/jgonfer/xcode-ui-testing-cheat-sheet

I've also created a blank new project with just the XCTest-Gherkin pod and I get the same error.

**Comment by kerrmarin** [comment]
Hey @jgonfer I have checked out your project and I can't seem to reproduce this same issue. Have you tried cleaning your build folder and running it again?

On a different note, I have found that using cocoapods in UI Tests doesn't work (see https://github.com/CocoaPods/CocoaPods/issues/5110) I think it will be fixed in the next version of CocoaPods.

**Comment by jgonfer** [comment]
Hi @kerrmarin I cleaned my build folder but I'm still getting the same error.

Related to your note about Cocoapods, [this comment](https://github.com/CocoaPods/CocoaPods/issues/5110#issuecomment-227041153) says that the PR should be included in next version. I'll check it again once the next version is released and I'll post here the results.

Thanks for your reply :)

**Comment by kerrmarin** [comment]
Great. I'll close this issue for now, if you are still finding issues after the next version of CocoaPods has been released please re-open.

Thanks!

**Comment by jgonfer** [comment]
Hi @kerrmarin ! I've found in this post https://github.com/CocoaPods/CocoaPods/issues/5250#issuecomment-220061976 a patch solution until next version of Cocoapods, and I can confirm you that XCTest and XCTest_Gherkin are working properly 👍 

![image](https://cloud.githubusercontent.com/assets/5473123/16554919/360a1b94-41d2-11e6-92ca-9b64374cc023.png)

I hope this post can be helpful.

**Comment by kerrmarin** [comment]
Awesome! Cheers @jgonfer
