### ISSUE TITLE
Installation of XCTest-Gherkin using carthage.

### ISSUE THREAD

**Issue by suniljakhar** [net-a-porter-mobile/XCTest-Gherkin#38]
Hi,
We are looking for installation of XCTest-Gherkin using carthage.

**Comment by kerrmarin** [comment]
Hi @suniljakhar. This would be a very cool addition to XCTest-Gherkin. We'll be happy to review a pull request that adds this functionality.

**Comment by nap-sam-dean** [comment]
Hi - I don't know anything about carthage really, but does this PR fix your problem - https://github.com/net-a-porter-mobile/XCTest-Gherkin/pull/47 ?

**Comment by ollitapa** [comment]
Hi, the scheme does not seem to be shared. It works if one checks the main scheme as shared in _Pods.xcodeproj. I can try to make a pull.

**Comment by nap-sam-dean** [comment]
@ollitapa Hi - is this issue fixed? (there's a PR for carthage here https://github.com/net-a-porter-mobile/XCTest-Gherkin/pull/47 but I don't use carthage so I don't know if it's working!) If this works with carthage now can you confirm so we can close this issue please? Thanks!

**Comment by ollitapa** [comment]
I can confirm the Carthage installation works.
