### ISSUE TITLE
Issue in Xcode 8

### ISSUE THREAD

**Issue by smaljaar** [net-a-porter-mobile/XCTest-Gherkin#44]
Hello! Today I ran in an issue using XCTest-Gherkin with Xcode 8. I can successfully use it and run the tests, until at the end of the run, Xcode crashes and it says:

> DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-11246/IDEFoundation/Testing/IDETestRunSession.m:399
> Details:  Unexpected test identifier SomethingSomething/testRunNativeTests() (expected (null)).

So XCTest does not seem to like this testRunNativeTests method which dynamically creates the other tests. I have tried removing the subclassing of NativeTestCase and setting the path directly within testRunNativeTests but it gave the same crash. Any ideas what to do or how to fix this?

Update: I just checked out the latest source from github XCTest-Gherkin and you can reproduce the issue there yourself. Steps:
1. open the file XCTest-Gherkin.xcworkspace
2. hit Command + U
3. See Xcode 8 crash

However, if you only run the tests that have Gherkin specified in Swift syntax, then Xcode does not crash. So the issue seem purely to be with the NativeTestCase class

**Comment by nap-sam-dean** [comment]
Hi - I'm working on this as we speak, but to be honest am not 100% sure why it's happening, and nothing I've tried so far has had any effect.

I've narrowed it down to running test cases from within another test case, but need to spend more time investigating.

**Comment by smaljaar** [comment]
I'm also looking into this but no luck so far. 
Any progress on your side?

**Comment by nap-sam-dean** [comment]
Nothing from me, but there's a PR that fixes it here: https://github.com/net-a-porter-mobile/XCTest-Gherkin/pull/45#pullrequestreview-416422 from @Rabursky - all it needs is the CI to pass and it looks good to go. And that's just a .travis configuration issue; the tests all pass locally :)

**Comment by nap-sam-dean** [comment]
@smaljaar Hi - can you confirm that the latest release of this fixes your problem, and then I can mark this issue as closed. Thanks!

**Comment by smaljaar** [comment]
@nap-sam-dean yes the latest release fixes it!

**Comment by nap-sam-dean** [comment]
Fantastic news :)
