### ISSUE TITLE
Native tests behave pretty weirdly with XCode's XCTest runner

### ISSUE THREAD

**Issue by jacdevos** [net-a-porter-mobile/XCTest-Gherkin#49]
Although more an issue in XCode, the way Native tests are dynamically built up does not play nicely with XCode's test runner, for one it does not show up until after running.

I've created a native runner, with you create normal XCUnit tests - and you simply pass in the feature file and scenario name. It works pretty well for my use case (in which we share the feature files between Android and iOS).

I will create a PR for this once my unit tests are done - just want to know if you see a value for this additional Native runner?

**Comment by kerrmarin** [comment]
Hey @jacdevos, thanks for thinking about contributing to XCTest-Gherkin. The native feature parsing is really just meant to be a way to onboard easily, but because of the current limitations for debugging, the recommended way to run tests with XCTest-Gherkin is to migrate your feature files to Swift. For this reason, I'm not sure we want to invest more time and effort into making the native parsing more user-friendly. I guess it depends on how "opinionated" we want this library to be -- I'll defer to @nap-sam-dean for an opinion.

In the meantime, thanks for helping!! And I'll look at your PR in the next couple of days 🚀 !

**Comment by jacdevos** [comment]
Hi Kerr Marin,

Thanks for considering! I would understand if you stick to your core use
case.

FYI the reasons I chose to build on your solution are:
• you support it well (only one to properly support Swift3 at the moment)
• the code is clean and modular, proved by how easy it was to support my
use case
• there just aren't good options to use XCode, XCUnit, XCUI tests (the only
Apple supported) with Gherkin (looked at https://github.com/kylef/Ploughman
, https://github.com/Ahmed-Ali/Cucumberish)

I love your Swift interface but our use case is to use the Gherkin scripts
shared between Android and iOS, defined mainly by a product owner and a
tester.

One thing that I will also need is firing testing events to make
integration into reports easy.

One option might be to move out all the native support into a separate
repo?

Cheers,
Jacques


On 17 Nov 2016, 7:31 PM +0200, Kerr Marin Miller <notifications@github.com>,
wrote:

Hey @jacdevos <https://github.com/jacdevos>, thanks for thinking about
contributing to XCTest-Gherkin. The native feature parsing is really just
meant to be a way to onboard easily, but because of the current limitations
for debugging, the recommended way to run tests with XCTest-Gherkin is to
migrate your feature files to Swift. For this reason, I'm not sure we want
to invest more time and effort into making the native parsing more
user-friendly. I guess it depends on how "opinionated" we want this library
to be -- I'll defer to @nap-sam-dean <https://github.com/nap-sam-dean> for
an opinion.

In the meantime, thanks for helping!! And I'll look at your PR in the next
couple of days 🚀 !

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/net-a-porter-mobile/XCTest-Gherkin/issues/49#issuecomment-261312807>,
or mute the thread

**Comment by smaljaar** [comment]
> I love your Swift interface but our use case is to use the Gherkin scripts
shared between Android and iOS, defined mainly by a product owner and a
tester.

We also reuse the same feature files for Android and iOS, and we love that this is possible with XCTest-Gherkin :)

**Comment by jacdevos** [comment]
This was resolved with the merging of PR #50 - and the ability to explicitly run Gherkin scenarios. Use the helpers NativeRunner.swift to achieve this now.

**Comment by kerrmarin** [comment]
Awesome! Thanks @jacdevos
