### ISSUE TITLE
TestCase Passes when it is actual failure

### ISSUE THREAD

**Issue by SpeedyNassir** [net-a-porter-mobile/XCTest-Gherkin#54]
I am pretty new to XCtest and I am from Testing background, still trying to grab hold of swift and XCtest.
Issue: I have updated the Pod yesterday, since then I am seeing my test passing even though it is a fail(Only when multiple tests are run from a class), it is all good when that specific test is run(ie. the test fails).

I am using :

```
extension XCTestCase {

    func waitForHittable(element: XCUIElement, waitSeconds: Double, file: String = #file, line: UInt = #line) {
        let existsPredicate = NSPredicate(format: "hittable == true")
        expectation(for: existsPredicate, evaluatedWith: element, handler: nil)   

        waitForExpectations(timeout: waitSeconds) { (error) -> Void in
            if (error != nil) {
                let message = "Failed to find \(element) after \(waitSeconds) seconds."
                self.recordFailure(withDescription: message,
                    inFile: file, atLine: line, expected: true)
            }
        }
}
```

What I found was that when multiple tests are run and method is called , if it is actual failure in second testcase then the test just proceeds as if nothing happened and it passes (self.recordFailure seems not working as expected for second one).But on the other hand if the actual failure is in first test the testcase fails.

**I have another machine with a bit older version of XCTest-Gherkin(around a month older version) and all is working as expected.Seems like the recent latest commit has broken something.**

Not sure If this issue has something to do with #48 (May be similar)

**Comment by nap-sam-dean** [comment]
Hi,

I can't reproduce this on the latest master (ref 7717628)

I'm using this test case to try to see the issue:

```
class FailingSecondTest: XCTestCase {

    func test0() {
        return
    }

    func test1() {
        self.expectation(description: "expectation")

        waitForExpectations(timeout: 1) { (error) -> Void in
            if (error != nil) {
                self.recordFailure(withDescription: "Test Failed",
                                   inFile: #file, atLine: #line, expected: true)
            }
        }
    }

    func test2() {
        self.expectation(description: "expectation")

        waitForExpectations(timeout: 1) { (error) -> Void in
            if (error != nil) {
                self.recordFailure(withDescription: "Test Failed",
                                   inFile: #file, atLine: #line, expected: true)
            }
        }
    }
}
```

but I get test0 passing, and test1 and test2 both fail as expected.

Can you product a test case which can be dropped into the pod's example project so I can reproduce it please?

**Comment by nap-sam-dean** [comment]
(I'll try to reproduce #48 - it does look like they might be the same issue)

**Comment by nap-sam-dean** [comment]
OK, I've tried this test case (in the UI test target) and it behaves as expected (i.e. 1 passing test, and then 2 failing ones).

```
extension XCTestCase {

    func waitForHittable(element: XCUIElement, waitSeconds: Double, file: String = #file, line: UInt = #line) {
        let existsPredicate = NSPredicate(format: "hittable == true")
        expectation(for: existsPredicate, evaluatedWith: element, handler: nil)

        waitForExpectations(timeout: waitSeconds) { (error) -> Void in
            if (error != nil) {
                let message = "Failed to find \(element) after \(waitSeconds) seconds."
                self.recordFailure(withDescription: message,
                                   inFile: file, atLine: line, expected: true)
            }
        }
    }
}

class FailingSecondTest: XCTestCase {

    func test0() {
        return
    }

    func test1() {
        let element = XCUIApplication().buttons["hunter1"]
        self.waitForHittable(element: element, waitSeconds: 1)
    }

    func test2() {
        let element = XCUIApplication().buttons["hunter2"]
        self.waitForHittable(element: element, waitSeconds: 1)
    }
}
```

This seems much closer to your original code, can you modify this so that it shows your issue please?

**Comment by SpeedyNassir** [comment]
@nap-sam-dean  yep when you write test as you mentioned above without gherkin and steps it works fine.The issue is when we use Gherkin as below:

I have tried the below using Gherkin:
Swift feature file like:

class Demo: XCTestCase {
    
    func test0(){
    Given("App is opened")
    }
    func test1(){
        Given("App is opened")
    }
    func test2(){
        Given("App is opened")
    }
}

and steps definitions goes like:

class LoginStepDefiner : StepDefiner {

    override func defineSteps() {
        step("App is opened"){
            let element = XCUIApplication().buttons["hunter2"]
            self.test.waitForHittable(element: element, waitSeconds: 1)
        }
    }
}

Test Result for above code:
The first test fails , but next 2 test passes
Like: Test2(Fail as expected)
Test1(Pass- Not Expected: Expected is failure)
Test0(Pass- Not Expected: Expected is failure)


I have added XCTestFail for func waitForHittable as:

**Added XCTFail  to fail test when recordFailure passes the failed test**


extension XCTestCase {

    func waitForHittable(element: XCUIElement, waitSeconds: Double, file: String = #file, line: UInt = #line) {
        let existsPredicate = NSPredicate(format: "hittable == true")
        expectation(for: existsPredicate, evaluatedWith: element, handler: nil)

        waitForExpectations(timeout: waitSeconds) { (error) -> Void in
            if (error != nil) {
                let message = "Failed to find \(element) after \(waitSeconds) seconds."
                self.recordFailure(withDescription: message,
                                   inFile: file, atLine: line, expected: true)
                 XCTFail(message) // Added to fail test when recordFailure passes the failed test 
            }
        }
    }
}

**Comment by deanWombourne** [comment]
Hey @SpeedyNassir - if your fix has worked for you can we close this issue?

Though I would recommend totally replacing self.recordFailure with XCTFail and passing in the line and file as well i.e. just use `XCTFail(message, file: file, line: line)` instead of the self.recordFailure line.

**Comment by SpeedyNassir** [comment]
Closing issue, Similar is tracked under #48
