### ISSUE TITLE
Add swiftlint* to keep coding style consistent

### ISSUE THREAD

**Issue by nap-sam-dean** [net-a-porter-mobile/XCTest-Gherkin#58]
\* or similar

**Comment by kerrmarin** [comment]
Is there a reference `.swiftlint.yml` for style or do we just go with the default?

**Comment by kerrmarin** [comment]
Also is it worth mentioning how we'd like this implemented? AFAIK there's two main ways of installing `swiftlint`: Homebrew and cocoapods -- presumably we only want homebrew support, since we don't necessarily want to have projects that depend on XCTest-Gherkin to have to install swiftlint... or do we?

And if we do go with the homebrew approach, we should add a section to the Installation readme that remings users to install swiftlint? So many questions 😄

**Comment by nap-sam-dean** [comment]
Hey. My 2c

1) I'd use a swiftlint.yml which most matches how we have coded so far, so it has minimal impact. I'm more interested in preserving consistency instead of forcing a standard on contributors.

2) I'd start with home-brew, mostly because travis CI (xcode8.3 image) has 0.17.0 pre-installed, which is the latest version. As swiftlint gets updated we might revisit this decision, depending on the time impact of updating travis each CI run (`brew update && brew upgrade swiftlint` is slower than you might expect, because of the initial update you need to run). 

2b) If we go down the cocoapods route, we would avoid users of the library from requiring it by just making it a requirement of the example app.

2c) I would assume that if we went down the cocoapods route, fast lane would explicitly refer to the swiftlint in the Pods folder, just in case there was another version installed somewhere else on $PATH

3) I wouldn't force contributors to have swiftlint installed, though I would obviously recommend it :)

4) I would create a lane in fast lane which lints the code - this would run in the CI, and would be with the `--strict` flag - i.e. warnings as errors :)

4) I would add a post build script into Xcode which runs swiftlint (exactly the same command as the CI, but without --strict) so that contributors (and us!) can see as fast as possible where they might get linting errors

4b) This post build script would not _require_ swiftlint - if it were missing, it would output an error, as in the swiftlint realm I believe.
