### ISSUE TITLE
Using NativeTestCase does not execute tests since initialise method change

### ISSUE THREAD

**Issue by smaljaar** [net-a-porter-mobile/XCTest-Gherkin#66]
There was a warning in Xcode 8.3 in NativeTestCase.swift 
`Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions`

@kerrmarin implemented an alternative in https://github.com/net-a-porter-mobile/XCTest-Gherkin/commit/f7d59064fe20006077a378b3a1876e8711438e23 which removes the warning, but this does not work. The tests are not executed anymore. 

The tests driven by the NativeRunner are working. My suggestion would be to delete the NativeTestCase.swift class and only use NativeRunner to drive test cases that are driven by native Gherkin feature files. This also cleans up some duplicate code between these classes.

**Comment by kerrmarin** [comment]
Hey @smaljaar! Thanks for reporting this. This is my bad, I have to admit I didn't realize my "fix" was being lazily initialized. I'll fix it in an upcoming PR, close this when it gets merged and then make a new issue to discuss removing `NativeTestCase` and replace with `NativeRunner`.

**Comment by kerrmarin** [comment]
This was fixed by #67
