### ISSUE TITLE
Xcode 9: improved logging of native Gherkin

### ISSUE THREAD

**Issue by smaljaar** [net-a-porter-mobile/XCTest-Gherkin#70]
# Issue 
Native Gherkin lines are not clearly traceable in Xcode results output

# Solution
New XCTContext.runActivity API in XCTest introduced in Xcode 9 makes it possible to wrap everything together that is executed within a native Gherkin step 🎉. See screenshot:

![xctest-gherkin-xcactivity 001](https://user-images.githubusercontent.com/2170746/27585304-0127cafa-5b3c-11e7-9724-cda36b548592.jpeg)

I am ready to make a pull request with this, but I decided to go via the Issue section first, especially because this is based on the Xcode 9 beta. See for the diff: https://github.com/net-a-porter-mobile/XCTest-Gherkin/compare/master...smaljaar:feature/xcode9-use-xcactivity-to-improve-native-logging?expand=1

Please let me know if any comments or suggestions.

**Comment by nap-sam-dean** [comment]
Love it! (Also, didn't know it existed until now!)

My only issue is backwards compatibility - is there a way that we can determine whether this is available and fall back to the legacy approach if it isn't? I don't know how quickly other uses of this library will move to Xcode 9 :|

**Comment by kerrmarin** [comment]
This is amazing 😍

**Comment by deanWombourne** [comment]
@kerrmarin @smaljaar Given we can't migrate to swift4 just yet (see #68, sigh) and xcode9 is live now, what do people think about just removing the version check (sorry, I know I was the one who asked for it in the first place!) and upping the version number to 0.11 ?

**Comment by kerrmarin** [comment]
Sound good to me. I did have a crack at #68 a while back but I got busy and it took a back seat. I'll see if I can think of something this weekend.

**Comment by deanWombourne** [comment]
Great - done here: https://github.com/net-a-porter-mobile/XCTest-Gherkin/pull/78

**Comment by deanWombourne** [comment]
I had a go at 68 too; I tried to write that bit in objective-c but I couldn't get the pod to build with a combination of swift and objc :(

**Comment by deanWombourne** [comment]
Right, this is in master, and tagged as 0.11.0 - it's pushing to the pod trunk repo as we speak, but over my home internet so give it a while. When it's pushed, I'll close this issue.
