### ISSUE TITLE
Fix for crash in ClassHelperMethods isn't available on the latest pod

### ISSUE THREAD

**Issue by saulbaro** [net-a-porter-mobile/XCTest-Gherkin#71]
Version 0.10.2 doesn't include commit 17ec271b148d6e831042d3f34162c6039590039c with the changes to `ClassHelperMethods.swift`. Our project tests fail due to that crash, and even if we have been able to work around this by pulling the latest master, it'll be nice to have a pod version to point to.

I can create a PR with a version bump myself to 0.10.3 if everyone is ok with it. Just wanted to check if that fits with your roadmap.

**Comment by nap-sam-dean** [comment]
I honestly thought I'd released that already (which tell you everything you need to know about our roadmap!)

A PR is very welcome :)

**Comment by saulbaro** [comment]
I've created the PR and I did all the steps listed in the [docs](https://guides.cocoapods.org/making/making-a-cocoapod.html#release), but since I have never published a pod I may have missed something.

**Comment by nap-sam-dean** [comment]
Hey.

That's pretty much it :) We usually update the changeling as well, but I realize that we don't have instructions to do that, so I've made an issue to get that fixed :)

I'll release this as soon as the CI is happy with master :)

**Comment by nap-sam-dean** [comment]
OK, 0.10.3 is released :)
