### ISSUE TITLE
Swift 4.0.2 support isn't available on the latest pod

### ISSUE THREAD

**Issue by jgonfer** [net-a-porter-mobile/XCTest-Gherkin#85]
Hi mates! I want to use the latest [version 0.12](https://github.com/net-a-porter-mobile/XCTest-Gherkin/releases/tag/0.12.0) in our project but I'm not able because the project crashes. The commit https://github.com/net-a-porter-mobile/XCTest-Gherkin/commit/4d2a39095bf849d8c8e4dabc692719b846c259aa includes all the necessary changes to fix the crash.

Do you have plans to release the next version?

**Comment by kerrmarin** [comment]
@deanWombourne can you release version 0.13, please?

**Comment by deanWombourne** [comment]
@kerrmarin  Sure - though you know you have permissions to push this pod up as well (I think - if not, we should give them to you!)

**Comment by deanWombourne** [comment]
@kerrmarin Wait, no - the second account isn't you, it's my net-a-porter.com email. sigh.

**Comment by deanWombourne** [comment]
OK, that's pushed as 0.13.1 (don't ask about 0.13.0, sigh)!

There's a few warnings about string.characters so I'll fix that and push out a 0.13.2 this evening.

**Comment by jgonfer** [comment]
Thanks a lot! 👏

**Comment by deanWombourne** [comment]
Here are the changes to remove the swift 4 warnings please? https://github.com/net-a-porter-mobile/XCTest-Gherkin/pull/87 - when this is approved I'll get it into master and released :)

**Comment by deanWombourne** [comment]
FYI: I've just pushed up version 0.13.2 which removes the compiler warnings :)

**Comment by jgonfer** [comment]
Thanks @deanWombourne, I've already updated the podfile with 0.13.2 😉
 Great job guys! 👏
