### ISSUE TITLE
Release 0.13.2 Swift compile error

### ISSUE THREAD

**Issue by JasonDobo** [net-a-porter-mobile/XCTest-Gherkin#88]
After updating to 0.13.2, all test runs started to have the following compile errors. Nothing else in the code has changed.
I got it working for now by going back to 0.12.0 in the podfile.

**Swift Compile Error:**
Pods/XCTest-Gherkin/Pod/Core/ClassHelperMethods.swift:53:46: Cannot convert value of type 'AutoreleasingUnsafeMutablePointer<AnyClass>' (aka 'AutoreleasingUnsafeMutablePointer<AnyObject.Type>') to expected argument type 'AutoreleasingUnsafeMutablePointer<AnyClass?>!' (aka 'ImplicitlyUnwrappedOptional<AutoreleasingUnsafeMutablePointer<Optional<AnyObject.Type>>>')

Pods/XCTest-Gherkin/Pod/Core/XCTestCase+Gherkin.swift:286:35: 'range(at:)' has been renamed to 'rangeAt(_:)'

/Pods/Foundation.NSTextCheckingResult:28:15: 'range(at:)' was introduced in Swift 4

**Comment by jgonfer** [comment]
Maybe you need to use **Xcode 9.1** which has Swift 4.0.2 support, because 0.13.2 is supporting that version as I reported in the issue https://github.com/net-a-porter-mobile/XCTest-Gherkin/issues/85.

**Comment by JasonDobo** [comment]
I am using Xcode 9.1

**Comment by deanWombourne** [comment]
Has your project migrated to Swift 4, or is it still using Swift 3? The error messages you're seeing look like you're compiling this library as a swift 3 project, not as swift 4. Version 0.12.0 is the last swift 3 version (assuming no catastrophic bugs) which is why that version works and 0.13.xx versions don't.

**Comment by JasonDobo** [comment]
The team is saying the project is Swift 4, but I'll go through and check all the targets

**Comment by deanWombourne** [comment]
Oh, that's interesting (read, surprising!). The project (and this libraries target) will be create automatically by cocoa pods (`pod install` etc) - which version of cocoa pods are you using so we can try to replicate this?

Also, you might have to force the swift version for specific pods (ours in this case) to a specific version - there's a post commit hook out can add to your pod file from this comment: https://github.com/CocoaPods/CocoaPods/issues/6791#issuecomment-329331953

**Comment by JasonDobo** [comment]
The podfile is getting the latest version of XCTest-Gherkin. I found the problem one of the targets was still set to Swift Language Version 3.2. Thank you for your help

**Comment by JasonDobo** [comment]
Cocoa pod version is 1.3.1

**Comment by deanWombourne** [comment]
No worries, glad we could help.
