### ISSUE TITLE
Using XCTestSuite in conjunction with XCTestCase

### ISSUE THREAD

**Issue by zacoid55** [net-a-porter-mobile/XCTest-Gherkin#89]
I'm sure you've already looked into this but is there any reason as to why the scenarios written using XCTest-Gherkin are separate XCTestCases within a XCTestSuite?

Just wondered if it might make controlling the full set of tests a bit easier? Giving you access to individual teardowns and startups for each case etc

**Comment by zacoid55** [comment]
(This is if, like me, your scenarios are all in one feature file)

**Comment by kerrmarin** [comment]
Hey @zacoid55. Sorry for the late reply. I personally hadn't considered having all scenarios in one feature file. I usually divide feature files by functionality. Would you mind elaborating a little more on what the issue you're having is? I'm not 100% sure I understand.
