### ISSUE TITLE
Error multiple step definitions while there aren't

### ISSUE THREAD

**Issue by MartijnSchoemaker** [net-a-porter-mobile/XCTest-Gherkin#90]
I have for example these steps defined:

```
step("This is a cool test step") {
   ...        
}
        
step("This is a cool test step with extras") {
   ...
}
```

In the feature file I use this step: "This is a cool test step with extras". 
This leads to an error "Multiple step definitions found for: This is a cool test step with extras". 

In the source I saw that this is caused by de regex to find the step definition.

**Comment by zacoid55** [comment]
We've been looking into the same thing recently and although it looks like it should happen on `firstMatch` of the whole string, it seems to pick a point where it deems it a duplicate if another step is close to it.

**Comment by MartijnSchoemaker** [comment]
Yes but it does first match on `This is cool test step` in `This is a cool test step with extras`

`if let match = step.regex.firstMatch(in: expression, options: [], range: range) {`

step = "This is cool test step"
expression = "This is a cool test step with extras"

**Comment by deanWombourne** [comment]
Can you remove ambiguity by adding the end of string capture flag to the first step?

```
step("This is a cool test step^") {
   ...        
}
```
