### ISSUE TITLE
[Feature Req] Catch Ambiguous matches.

### ISSUE THREAD

**Issue by JoseSanchezMirandaRos** [net-a-porter-mobile/XCTest-Gherkin#91]
It's be nice if the suite would tell you if a step is too similar to the next one. In this case, it reads the third step and executes the second step again.  Screenshots attached. 
<img width="456" alt="screen shot 2018-01-19 at 2 17 07 pm" src="https://user-images.githubusercontent.com/10212034/35174229-78da3bda-fd23-11e7-9349-e51555830bfb.png">
<img width="790" alt="screen shot 2018-01-19 at 2 17 44 pm" src="https://user-images.githubusercontent.com/10212034/35174250-8a860102-fd23-11e7-96bd-ed06185dcdb1.png">

**Comment by kerrmarin** [comment]
Hi @JoseSanchezMirandaRos. Thanks for the report. The easiest way to get around this problem is to use a start and end delimeter for your regular expression. Change `I tap the (.*) button` regex to `^I tap the (.*) button$`. That will remove the ambiguity.

**Comment by JoseSanchezMirandaRos** [comment]
No worries, thanks for the hard work! very happy I found this.
