### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by tomesm** [net-a-porter-mobile/XCTest-Gherkin#92]
Hi I am wondering if there is a plan to create and share Carthage files with you library. We do not use pods in our team.

**Comment by kerrmarin** [comment]
Hi @tomesm, I'm not sure I understand your question but XCTest-Gherkin should be compatible with Carthage, you just have to add it to your Cartfile like: `github "net-a-porter-mobile/XCTest-Gherkin" == 0.13.2`.

**Comment by tomesm** [comment]
Ok. I had no idea that the project is compatible with Carthage. Perhaps it would be worth mentioning in the "Install" section of the README.

**Comment by kerrmarin** [comment]
Great idea :) https://github.com/net-a-porter-mobile/XCTest-Gherkin/pull/94
