### ISSUE TITLE
Error during compilation with XCode Version 9.3.1 (9E501)

### ISSUE THREAD

**Issue by obrizan** [net-a-porter-mobile/XCTest-Gherkin#99]
When compiling XCTest-Gherking v. 0.14.0 with XCode Version 9.3.1 (9E501) I got:
 
```
./Pods/XCTest-Gherkin/Pod/Core/ClassHelperMethods.swift:53:46: 
Cannot convert value of type 'AutoreleasingUnsafeMutablePointer<AnyClass>' 
(aka 'AutoreleasingUnsafeMutablePointer<AnyObject.Type>') 
to expected argument type 'AutoreleasingUnsafeMutablePointer<AnyClass?>!' 
(aka 'ImplicitlyUnwrappedOptional<AutoreleasingUnsafeMutablePointer<Optional<AnyObject.Type>>>')
```

**Comment by deanWombourne** [comment]
How annoying - I don't get any updates for Xcode but I'm still on 9.3.0 so I'm downloading the 9.4 beta to see if I can replicate this issue there.

Which version of Swift is bundled with 9.3.1? (`swift --version` on the command line will tell you).

**Comment by deanWombourne** [comment]
OK, that's even more strange - that's the version I'm on, and it compiles fine :|

**Comment by deanWombourne** [comment]
I've just built and tested with Xcode 9.4 and it seems to work for me? I can't seem to reproduce this at all :|

**Comment by obrizan** [comment]
In 9.4.1 works fine, I'm closing the issue.
